In [126]:
import torch
import time

In [121]:
outs = torch.rand(60,14000)
outs = torch.nn.Softmax(dim=1)(outs)
outs.shape

torch.Size([60, 14000])

In [122]:
sample = torch.rand(60, 1)

In [123]:
outs, sample

(tensor([[5.0265e-05, 9.4343e-05, 7.2895e-05,  ..., 1.0489e-04, 8.5728e-05,
          8.7574e-05],
         [4.7576e-05, 6.9189e-05, 8.1051e-05,  ..., 4.7016e-05, 9.8384e-05,
          1.1107e-04],
         [5.6454e-05, 7.7577e-05, 4.8128e-05,  ..., 7.6844e-05, 9.4510e-05,
          7.0611e-05],
         ...,
         [1.0320e-04, 4.5618e-05, 6.6341e-05,  ..., 7.1400e-05, 6.3279e-05,
          5.6838e-05],
         [6.1543e-05, 8.6616e-05, 1.0854e-04,  ..., 1.1092e-04, 7.5482e-05,
          9.6659e-05],
         [4.1864e-05, 9.2298e-05, 1.0822e-04,  ..., 6.2814e-05, 1.0715e-04,
          4.6244e-05]]),
 tensor([[0.2079],
         [0.9143],
         [0.0292],
         [0.4371],
         [0.4290],
         [0.3254],
         [0.7046],
         [0.5316],
         [0.8286],
         [0.8177],
         [0.0594],
         [0.2540],
         [0.6584],
         [0.8014],
         [0.0327],
         [0.8471],
         [0.8286],
         [0.8116],
         [0.3896],
         [0.1161],
         [

In [127]:
start = time.time()
sums = torch.zeros(outs.shape)
sums[:, 0:1] = outs[:, 0:1]
for i in range(1, outs.shape[1]):
    sums[:, i:i+1] = sums[:, i-1:i] + outs[:, i:i+1]
print(time.time() - start)
sums

0.2675204277038574


tensor([[5.0265e-05, 1.4461e-04, 2.1750e-04,  ..., 9.9983e-01, 9.9991e-01,
         1.0000e+00],
        [4.7576e-05, 1.1676e-04, 1.9782e-04,  ..., 9.9979e-01, 9.9989e-01,
         1.0000e+00],
        [5.6454e-05, 1.3403e-04, 1.8216e-04,  ..., 9.9984e-01, 9.9993e-01,
         1.0000e+00],
        ...,
        [1.0320e-04, 1.4881e-04, 2.1515e-04,  ..., 9.9988e-01, 9.9994e-01,
         1.0000e+00],
        [6.1543e-05, 1.4816e-04, 2.5670e-04,  ..., 9.9983e-01, 9.9990e-01,
         1.0000e+00],
        [4.1864e-05, 1.3416e-04, 2.4238e-04,  ..., 9.9985e-01, 9.9996e-01,
         1.0000e+00]])

In [125]:
tmp = torch.arange(outs.shape[1], 0, -1)
tmp2 = torch.where(sample > sums, torch.tensor(1), torch.tensor(-1))
print(tmp * tmp2)
torch.argmin(tmp * tmp2, 1, keepdims=True)

tensor([[14000, 13999, 13998,  ...,    -3,    -2,    -1],
        [14000, 13999, 13998,  ...,    -3,    -2,    -1],
        [14000, 13999, 13998,  ...,    -3,    -2,    -1],
        ...,
        [14000, 13999, 13998,  ...,    -3,    -2,    -1],
        [14000, 13999, 13998,  ...,    -3,    -2,    -1],
        [14000, 13999, 13998,  ...,    -3,    -2,    -1]])


tensor([[ 2875],
        [12812],
        [  409],
        [ 6118],
        [ 6000],
        [ 4562],
        [ 9846],
        [ 7428],
        [11574],
        [11423],
        [  846],
        [ 3554],
        [ 9197],
        [11212],
        [  451],
        [11856],
        [11603],
        [11345],
        [ 5457],
        [ 1624],
        [ 1789],
        [ 4744],
        [ 6734],
        [ 7814],
        [ 6276],
        [ 3578],
        [11259],
        [13460],
        [ 4362],
        [ 8767],
        [ 2537],
        [10272],
        [10149],
        [ 5454],
        [ 5247],
        [10152],
        [ 1889],
        [ 9784],
        [13035],
        [ 6891],
        [11065],
        [ 2390],
        [ 7208],
        [ 7518],
        [ 8836],
        [ 8491],
        [ 8791],
        [10898],
        [ 2209],
        [ 4505],
        [13491],
        [ 2273],
        [13739],
        [ 7165],
        [ 2570],
        [ 2299],
        [ 5382],
        [ 1110],
        [ 9659